"""Test

Revision ID: 1b1163b959a5
Revises: 57669ef426e4
Create Date: 2023-09-25 01:36:46.611654

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1b1163b959a5'
down_revision: Union[str, None] = '57669ef426e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
