"""add default value

Revision ID: 3f3560c7d7fd
Revises: 9560c0dab43e
Create Date: 2023-09-24 23:33:13.051206

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f3560c7d7fd'
down_revision: Union[str, None] = '9560c0dab43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("INSERT INTO roles (name) VALUES ('Admin'), ('User')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
