"""Insert data into roles table

Revision ID: 57669ef426e4
Revises: 4dc13ed861d5
Create Date: 2023-09-25 00:31:42.971870

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '57669ef426e4'
down_revision: Union[str, None] = '4dc13ed861d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
