"""initial

Revision ID: 9560c0dab43e
Revises: 
Create Date: 2023-09-24 18:35:04.656154

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9560c0dab43e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
